Check if the alientype is valid before trying to call it. This provides a less aggressive error output

diff --git a/bin/Alien b/bin/Alien
--- a/bin/Alien
+++ b/bin/Alien
@@ -36,4 +36,9 @@ fi
 alientype="${prog%%:*}"
 alienpkg="${prog#*:}"
 shift 2
+if [[ ! -x /System/Index/bin/Alien-$alientype ]]
+then
+    echo "Error: $alientype is not a valid alientype"
+    exit 1
+fi
 exec Alien-$alientype $mode $alienpkg "$@"
