Give list of versions with errors from DisableProgram and RemoveProgram too. Fixes #234 more completely.

diff --git a/bin/DisableProgram b/bin/DisableProgram
--- a/bin/DisableProgram
+++ b/bin/DisableProgram
@@ -29,10 +29,16 @@ if [ "$(Arg 2)" ]
 then versionnumber="$(Arg 2)"
 else versionnumber=`Get_Version "$programname" "Current"`
 fi
-[ -z "${versionnumber}" ] && Die "No current version found and no version specified."
+if [ -z "${versionnumber}" ]
+then
+   Die "No current version found and no version specified. Available versions are:\n$(Installed_Versions "$programname")"
+fi
 prefix="${goboPrograms}/$programname/$versionnumber"
 
-Is_Directory "$prefix" || Die "$programname version $versionnumber was not found."
+if ! Is_Directory "$prefix"
+then
+   Die "$programname version $versionnumber was not found. Available versions are:\n$(Installed_Versions "$programname")"
+fi
 
 Log_Normal "Disabling ${programname}, version ${versionnumber}."
 
diff --git a/bin/RemoveProgram b/bin/RemoveProgram
--- a/bin/RemoveProgram
+++ b/bin/RemoveProgram
@@ -25,14 +25,18 @@ Verify_Superuser
 appname=$(Arg 1)
 appver=$(Arg 2)
 [ "${appname}" ] || Die "Argument missing: specify the program name."
-[ "${appver}" ] || Die "Argument missing: specify the program version."
+if ! [ "${appver}" ]
+then
+   Die "Argument missing: specify the program version.\nAvailable versions are:\n$(Installed_Versions "$appname")"
+fi
 
 program=`GuessProgramCase ${appname} ${appver}`
 version=${appver}
 
 if [ ! -d ${goboPrograms}/${program}/${version} ]
 then
-   Die "${program} ${version} not found at ${goboPrograms}"
+   [ ! -d "${goboPrograms}/${program}" ] && Die "${program} not found in ${goboPrograms}"
+   Die "${program} ${version} not found in ${goboPrograms}. Available versions:\n$(Installed_Versions "$appname")"
 fi
 
 Log_Terse "Removing $program, version $version."
