Revert use of ${symlink} since we depend on it in a "case". Remove interactivity when same version is found. By default we cancel, but behaviour can be changed with call time option "--same".

diff --git a/bin/InstallPackage b/bin/InstallPackage
--- a/bin/InstallPackage
+++ b/bin/InstallPackage
@@ -32,7 +32,7 @@ Add_Option_Entry "u" "unmanaged" "Defines what to do with unmanaged files from p
 Add_Option_Boolean "C" "no-sign-check" "Do not check the signature."
 Add_Option_Boolean "U" "no-updatesettings" "Do not update settings for the package"
 Add_Option_Boolean "W" "no-web" "Do not check remote site for packages, and bypass fetching of archives."
-  
+
 Parse_Options "$@"
 
 if [ -z "$ROOTLESS_GOBOLINUX" ] && ! $sudo_validate
@@ -51,7 +51,7 @@ then
 fi
 
 unmanaged="--unmanaged $(Entry unmanaged)"
-symlink="--symlink $(Entry symlink)"
+symlink="$(Entry symlink)"
 same="--same $(Entry same)"
 old="--old $(Entry old)"
 Boolean "batch"      && batch="--batch"
@@ -78,19 +78,19 @@ then
 
    if [ "${keep}" ]
    then   
-      . "`Find_Conf GetAvailable.conf`" || Die "Couldn't read GetAvailable.conf"
+      Parse_Conf --mandatory GetAvailable.conf || Die "Couldn't read GetAvailable.conf"
       [ -d "${defaultLocalPackagesPaths[0]}" ] || mkdir -p "${defaultLocalPackagesPaths[0]}"
       Log_Normal "Moving package to ${defaultLocalPackagesPaths[0]}/${filename}."
 
       if mv "${goboTemp}/${filename}" "${defaultLocalPackagesPaths[0]}/${filename}"
       then 
-         InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${defaultLocalPackagesPaths[0]}/${filename}"
+         InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink:+--symlink=${symlink}} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${defaultLocalPackagesPaths[0]}/${filename}"
       else
          Log_Error "Could not move package."
-         InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${goboTemp}/${filename}"
+         InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink:+--symlink=${symlink}} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${goboTemp}/${filename}"
       fi
    else
-      InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${goboTemp}/${filename}"
+      InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink:+--symlink=${symlink}} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${goboTemp}/${filename}"
       Log_Normal "Removing downloaded package ${goboTemp}/${filename}."
       rm -f -- "${goboTemp}/${filename}"
    fi
@@ -130,7 +130,7 @@ then
          if [ "${found}" ]
          then 
             Log_Normal "Found package for ${name} ${version}: ${found}"
-            InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${found}"
+            InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink:+--symlink=${symlink}} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${found}"
          else
             Die_With $errorNotFound "Package for ${name} ${version} not found."
          fi
@@ -139,7 +139,7 @@ then
          if [ "${found}" ]
          then
             [ ! "$batch" ] && Ask_Continue "Installing ${found}"
-            InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${found}"
+            InstallPackage ${unmanaged} ${usecontrib} ${noinstall} ${symlink:+--symlink=${symlink}} ${same} ${old} ${nosigncheck} ${keep} ${batch} "${found}"
          else
             Die_With $errorNotFound "Package for ${name} not found."
          fi
@@ -227,29 +227,12 @@ existingpackage=`ls "${goboPrograms}" | grep -i "^$packagename$"`
    
    if [ -e "${goboPrograms}/$existingpackage/$packageversion" ]
    then
-      Is_Entry "same" "cancel" && Pass_Away "Attempting to install $packagename over same version."
+      Is_Entry "same" "cancel" && Pass_Away "Not attempting to install $packagename over same version."
       Is_Entry "same" "remove" && doremove=yes
-      Is_Entry "same" "ask" && {
-         Log_Question "An installation of this same version already exists."
-         doremove=yes
-         doask=yes
-      }
    fi
 }
 
-function try_remove() {
-   [ "$doremove" = "yes" ] && {
-      [ "$doask" = "yes" ] && {
-         Ask_Option "Remove existing? [R]emove/[k]eep/[c]ancel" "R" '[ -n "$REPLY" -a -z "$(echo $REPLY | sed -r -e "s/((R|r)|(K|k)|(C|c))//")" ]'
-         echo
-         [ "$REPLY" = "C" -o "$REPLY" = "c" ] && exit 1
-         [ "$REPLY" = "K" -o "$REPLY" = "k" ] && return
-      }
-      rm -rf -- "${goboPrograms}/$existingpackage/$packageversion"
-   }
-}
-
-try_remove
+[ "yes" = "$doremove" ] && Pre_Installation_Preparation ${packagename} ${packageversion}
 
 Log_Normal "Installing $packagename, version $packageversion."
 
@@ -324,11 +307,13 @@ else
    then
       Log_Error "Invalid signature. FileHash could not be verified."
       Log_Error "Suspect package in ${goboPrograms}/$packagename/$packageversion"
+      [ "yes" = "$doremove" ] && Post_Installation_Clean_Up ${packagename} ${packageversion} "failed"
       exit 1
    elif [ $result -eq 1 ]
    then
       Log_Error "Invalid FileHash. Package has been modified"
       Log_Error "Suspect package in ${goboPrograms}/$packagename/$packageversion"
+      [ "yes" = "$doremove" ] && Post_Installation_Clean_Up ${packagename} ${packageversion} "failed"
       exit 1
    fi
 fi
@@ -383,6 +368,7 @@ case "${symlink}" in
 "force") SymlinkProgram ${unmanaged} --conflict=overwrite "$packagename" "$packageversion" ;;
 esac
 
+[ "yes" = "$doremove" ] && Post_Installation_Clean_Up ${packagename} ${packageversion}
 [ "$package_verified" = "true" ] && Run_PostInstall "$packagename" "$packageversion" "" ""
 
 
@@ -398,7 +384,7 @@ then
       set +o pipefail
       for d_url in $selecteddeps
       do
-         InstallPackage --no-dependencies ${unmanaged} ${usecontrib} ${noinstall} ${symlink} ${same} ${old} ${nosigncheck} ${keep} ${batch} $d_url || {
+         InstallPackage --no-dependencies ${unmanaged} ${usecontrib} ${noinstall} ${symlink:+--symlink=${symlink}} ${same} ${old} ${nosigncheck} ${keep} ${batch} $d_url || {
             ret=$?
             exit $ret
          }
