Clean up GoboLinux function module by moving all metadata installation functions to a MetadataInstallation module Move link_directory() from SymlinkProgram executable to GoboLinux module

diff --git a/Functions/GoboLinux b/Functions/GoboLinux
--- a/Functions/GoboLinux
+++ b/Functions/GoboLinux
@@ -46,120 +46,32 @@ function Parse_Version() {
     fi
 }
 
-function Gen_Env_Cache() {
-   Log_Verbose "Rebuilding environment cache..."
-   cache="$goboEnvironment"/Cache
-   echo -e "unset unsetvars\n[ ! \"\$goboSettings\" ] && unsetvars=true\n" > "$cache"
-   echo -e "source GoboPath\n" >> "$cache"
-   for linkedfile in "$goboEnvironment"/*--*
-   do 
-      [ -f "$linkedfile" ] && cat "$linkedfile" >> "$cache"
-      echo >> "$cache"
-   done
-   unsetvars="$(grep export "$goboExecutables/GoboPath" | awk {'print $1 " " $2'} | grep "^export" | sed -e 's,=.*,,g' -e 's,export,unset,g')"
-   echo -e "if [ \"\$unsetvars\" ]\nthen\n$unsetvars\nfi\n" >> "$cache"
-}
+# Creates links from one directory into another.
+function link_directory() {
+   Parameters "$@" from to
+   local rfrom here j
 
-function Rebuild_GDK_Pixbuf_Loaders() {
-if Executable_Exists_In_Path "gdk-pixbuf-query-loaders"
-then
-   loadersfile="${goboSettings}/gtk-2.0/gdk-pixbuf.loaders"
-   gdk-pixbuf-query-loaders | $sudo_exec dd of=${loadersfile} 2> /dev/null
-fi
-}
+   rfrom=`readlink -f "$from"`
 
-function Rebuild_MIME_Database() {
-if Executable_Exists_In_Path "update-mime-database"
-then
-   mimedirectory="${goboVariable}/xdg/mime"
-   if ! $sudo_exec mkdir -p ${mimedirectory} && ! $sudo_exec test -w ${mimedirectory}
-   then [ -n "${XDG_DATA_HOME}" ] && mimedirectory="${XDG_DATA_HOME}/mime" || mimedirectory="$HOME/.local/share/mime"
-   fi
-   Assert_Dir ${mimedirectory}
-   Is_Directory ${mimedirectory}/packages || $sudo_exec ln -s ${goboShared}/mime/packages ${mimedirectory}
-   Log_Normal "Rebuilding MIME database..."
-   $sudo_exec update-mime-database ${mimedirectory} >/dev/null
-fi
-}
-
-function Rebuild_Desktop_Database() {
-if Executable_Exists_In_Path "update-desktop-database"
-then
-   desktopdirectory="${goboVariable}/xdg"
-   if ! $sudo_exec mkdir -p $desktopdirectory && ! $sudo_exec test -w ${desktopdirectory}
-   then [ -n "${XGD_DATA_HOME}" ] && desktopdirectory="${XDG_DATA_HOME}" || desktopdirectory="$HOME/.local/share"
-   fi
-   Assert_Dir ${desktopdirectory}
-   Is_Directory ${desktopdirectory}/applications || ln -s ${goboShared}/applications ${desktopdirectory}
-   Log_Normal "Rebuilding desktop database..."
-   update-desktop-database ${desktopdirectory}
-fi
-}
-
-function Rebuild_Font_Cache() {
-if Executable_Exists_In_Path "fc-cache"
-then
-   Log_Normal "Updating font cache..."
-   fc-cache
-fi
-}
-
-function Add_To_XML_Catalog() {
-target="${1}"
-xmldatafile="${target}/Resources/XmlCatalogData"
-if Executable_Exists_In_Path "xmlcatalog"
-then
-   while read data
-   do
-      type="$(echo ${data} | cut -d';' -f1)"
-      orig="$(echo ${data} | cut -d';' -f2)"
-      eval repl="$(echo ${data} | cut -d';' -f3)"
-      eval catalog="$(echo ${data} | cut -d';' -f4)"
-      [ -f "${catalog}" ] || { Assert_Dir $(dirname "${catalog}"); xmlcatalog --noout --create "${catalog}"; }
-      xmlcatalog --noout --add ${type} "${orig}" "${repl}" "${catalog}"
-   done < "${xmldatafile}"
-fi
-}
-
-function Update_Scrollkeeper_Database() {
-if Executable_Exists_In_Path "scrollkeeper-update"
-then
-   Log_Normal "Updating scrollkeeper catalog..."
-   scrollkeeper-update -q &>/dev/null
-fi
-}
-
-function Remove_From_XML_Catalog() {
-target="${1}"
-xmldatafile="${target}/Resources/XmlCatalogData"
-if Executable_Exists_In_Path "xmlcatalog"
-then
-   while read data
-   do
-      orig="$(echo ${data} | cut -d';' -f2)"
-      eval catalog="$(echo ${data} | cut -d';' -f4)"
-      [ -f "${catalog}" ] && xmlcatalog --noout --del "${orig}" "${catalog}"
-   done < "${xmldatafile}"
-fi
-}
-
-function Uninstall_GConf_Schemas() {
-   Parameters "$@" application_name
-   if Executable_Exists_In_Path "gconftool-2"
+   if ! Is_Empty_Directory "$rfrom"
    then
-      export GCONF_CONFIG_SOURCE=$(gconftool-2 --get-default-source)
-      gconftool-2 --makefile-uninstall-rule ${goboPrograms}/${application_name}/Settings/gconf/schemas/*.schemas >/dev/null
-      killall -HUP gconfd-2 &> /dev/null
-   fi
-}
+      here=`readlink -f "$to"`
+      [ -d "$here" ] || mkdir "$here"
+      cd "$here"
 
-function Install_GConf_Schemas() {
-   Parameters "$@" application_name
-   if Executable_Exists_In_Path "gconftool-2"
-   then
-      export GCONF_CONFIG_SOURCE=$(gconftool-2 --get-default-source)
-      gconftool-2 --makefile-install-rule ${goboPrograms}/${application_name}/Settings/gconf/schemas/*.schemas >/dev/null
-      killall -HUP gconfd-2 &> /dev/null
+      Boolean "relative" && relative="--relative" || relative=""
+      [ "${conflict}" = "overwrite" ] && overwrite="--overwrite" || overwrite=""
+      if [ -n "$(type -p LinkOrExpandAll)" ]
+      then
+         LinkOrExpandAll "$rfrom" "$overwrite" "$relative"
+      else
+         Log_Error "LinkOrExpandAll not found.  Fallback to python code."
+         Boolean "relative" && relative="True" || relative="False"         
+         Link_Or_Expand_All "$rfrom" "$overwrite" "$relative"
+      fi
+      cd "$here"
+   else
+      Quiet rmdir "$rfrom"
    fi
 }
 
@@ -712,69 +624,6 @@ import pwd
 entry=pwd.getpwuid(0)
 print entry[0]
 '
-}
-
-function Install_Unmanaged_Files() {
-   Parameters "$@" unmanagedfilesfile sourcedir
-   local kernelversion="`readlink $goboModules/Current 2> /dev/null`"
-   [ ! "$kernelversion" ] && kernelversion="$(uname -r)"
-   if [ -f "$unmanagedfilesfile" ]
-   then
-      grep -E -v "^(\./|/|)Programs" "$unmanagedfilesfile" | while read line
-      do
-         local dname=$(dirname "${goboPrefix}/$line")
-         mkdir -p "${dname}"
-         Quiet cp -a "${sourcedir}/${line}" "${dname}/"
-      done
-      if grep -q "${goboModules}" "$unmanagedfilesfile"
-      then 
-         Log_Normal "Calculating kernel module dependencies..."
-         depmod -ae ${kernelversion}
-      fi
-   fi
-}
-
-function Uninstall_Unmanaged_Files() {
-   Parameters "$@" unmanagedfilesfile interactive
-   local kernelversion="`readlink $goboModules/Current 2> /dev/null`"
-   [ ! "$kernelversion" ] && kernelversion="$(uname -r)"
-   if [ -f "${unmanagedfilesfile}" ]
-   then
-      for line in $(grep -E -v "^(\./|/|)Programs" "$unmanagedfilesfile")
-      do
-         local dname=$(dirname "${goboPrefix}$line")
-         if [ -n "${interactive}" ]
-         then
-            if Ask "Remove ${goboPrefix}${line}?"
-            then rm -fr "${goboPrefix}${line}"
-            else continue
-            fi
-         elif [ -d "${goboPrefix}${line}" ]
-         then
-            Log_Verbose "${goboPrefix}${line}"
-            rmdir "${goboPrefix}${line}" 2>/dev/null || echo "${goboPrefix}${line}"
-         else
-            Log_Verbose "${goboPrefix}${line}"
-            rm -f "${goboPrefix}${line}"
-         fi
-         Quiet rmdir "${dname}"
-       done
-      if grep -q "${goboModules}" "$unmanagedfilesfile"
-      then 
-         Log_Normal "Calculating kernel module dependencies..."
-         depmod -ae ${kernelversion}
-      fi
-   fi
-}
-
-function String_Revision() {
-   Parameters "$@" versionandrevision
-   echo $versionandrevision | sed -nr 's,.*-(r[0-9]+(p[0-9]+)?)$,\1,p'
-}
-
-function String_Version() {
-   Parameters "$@" versionandrevision
-   echo $versionandrevision | sed -r 's/-r[0-9]+(p[0-9]+)?$//g'
 }
 
 function Get_System_Paths () {
