r40@Hermes:  jonas | 2008-03-18 11:33:32 +0100  If a group with the same name as $user exists, we can asume that we want to add $user to that group. If we don't specify any group in this case useradd will die.  Also redirecting useradd message to Log_Verbose.

diff --git a/Functions/Requirements b/Functions/Requirements
--- a/Functions/Requirements
+++ b/Functions/Requirements
@@ -94,11 +94,15 @@ function Process_Requirements_File() {
             uid="`get_next_system_id $goboSettings/passwd`"
             [ ! "$uid" ] && { Log_Error "Could not add user $user: no free slots"; continue; }
          fi
+         grep -q "$user" "${goboSettings}/group" && maingroup="${user}"
          Log_Normal "Adding user $user..."
          [ -d "$homedir" ] && createhomedir= || createhomedir="-m"
-         $sudo_exec useradd --uid $uid -c "Added by $package $version" $createhomedir -d "$homedir" -s "$goboExecutables/nologin" $user
+         useraddmsg=$($sudo_exec useradd --uid $uid -c "Added by $package $version" $createhomedir -d "$homedir" -s "$goboExecutables/nologin" ${maingroup:+-g "${maingroup}"} $user 2>&1)
          [ "$groups" ] && $sudo_exec usermod -a -G "$groups" "$user"
-         grep -q "^$user:" $goboSettings/passwd || Log_Error "Error adding user $group."
+         grep -q "^$user:" $goboSettings/passwd || {
+	    Log_Error "Error adding user $user"
+	    Log_Verbose "Reason: ${useraddmsg}"
+	 }
       done
    fi
 }
